.drone.yml, docker-compose.yml
1 despliegue de cuentas contables crud
=> Dev -> Test Dec 26 Se agrega .drone.yml

entrypoint.sh
Dev -> Test Dec 26 Se corrigen varibles de BD en el entrypoint
=> Dev -> Test Dec 26 Se corrigen varibles de BD en el entrypoint

compositors/nodo_cuenta_contable.compositor.go, controllers/comprobante.go, controllers/nodo_cuenta_contable.go, controllers/tipo_comprobante.go, managers/nodo_cuenta_contable.manager.go, swagger/swagger.json, swagger/swagger.yml
=> fixed code issues and added fullTree flag

go.mod, go.sum, main.go
=> se agrega funcionalidad cors y de auditoria

managers/crud.manager.go
se agrega linea para que maneje modelos sin codigo y que tome el objectID autogenerado
=> add line to manage struct without code

compositors/comprobante.compositor.go, conf/app.conf, controllers/comprobante.go, go.mod, go.sum, managers/comprobante.manager.go, managers/consecutivo.manager.go, models/comprobante.go, swagger/swagger.json, swagger/swagger.yml
se corrige error de las transacciones en la parametrizacion de los comprobantes
#8
=> resolve transaction receipt

compositors/comprobante.compositor.go, conf/app.conf, controllers/comprobante.go, go.mod, go.sum, managers/comprobante.manager.go, managers/consecutivo.manager.go, managers/crud.manager.go, models/comprobante.go, swagger/swagger.json, swagger/swagger.yml
=> Dev -> Test 8/jan./20 parametros comprobantes

controllers/comprobante.go, controllers/tipo_comprobante.go, managers/tipo_comprobante.manager.go, routers/commentsRouter_controllers.go, swagger/swagger.json, swagger/swagger.yml
se resuelve error de ruteo de componentes y se corrige error del update cuando el item es el mismo
[Issue](https://github.com/udistrital/contabilidad_cliente/issues/7)
=> resolve route and item exits by ID

controllers/comprobante.go, controllers/tipo_comprobante.go, entrypoint.sh, managers/tipo_comprobante.manager.go, routers/commentsRouter_controllers.go, swagger/swagger.json, swagger/swagger.yml
[Issue #7](https://github.com/udistrital/contabilidad_cliente/issues/7)
=> Dev -> Test 14/jan./20 Control de errores comprobantes

tests/comprobantestestcases/comprobante_test.go, tests/comprobantestestcases/default_test.go, tests/comprobantestestcases/tipo_comprobante_test.go
#8 Agregados test para los procesos
=> add test to process tipo_comprobantes and comprobantes

controllers/centro_costos.go, migrations/20200118_centro_costos.go, models/centro_costos.go, routers/commentsRouter_controllers.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml
=> Add centro costos coll

compositors/comprobante.compositor.go, compositors/tipo_comprobante.compositor.go, controllers/centro_costos.go, controllers/comprobante.go, controllers/detalle_cuenta_contable.go, controllers/naturaleza_cuenta_contable.go, controllers/nodo_cuenta_contable.go, controllers/tipo_comprobante.go, controllers/tipo_moneda.go, helpers/nodo_cuenta_contable.helper.go, main.go, managers/consecutivo.manager.go, managers/crud.manager.go, models/centro_costos.go, models/comprobante.go, models/detalle_cuenta_contable.go, models/naturaleza_cuenta_contable.go, models/nodo_cuenta_contable.go, models/tipo_comprobante.go, models/tipo_moneda.go, swagger/swagger.json, swagger/swagger.yml, tests/testmanagers/default_test.go
Se realizan correcciones que aparecen en el [drone](https://hubci.portaloas.udistrital.edu.co/udistrital/cuentas_contables_crud/64/1/3).
[Issue #49](https://github.com/udistrital/financiera_documentacion/issues/49)
=> Correcciones errores drone

controllers/concepto.go, managers/crud.manager.go, models/concepto.go, routers/commentsRouter_controllers.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml
[Issue #25 ](https://github.com/udistrital/contabilidad_cliente/issues/25)
=> Added CRUD op for concepto model

models/concepto.go, swagger/swagger.json, swagger/swagger.yml
[Issue #25](https://github.com/udistrital/contabilidad_cliente/issues/25)
=> Se modifica modelo de conceptos :octocat:

models/nodo_cuenta_contable.go
Relacionado con udistrital/arka_cliente#574
=> feat: Ajuste Contable

controllers/nodo_cuenta_contable.go, managers/nodo_cuenta_contable.manager.go, models/nodo_cuenta_contable.go
feat: ajuste para primer migrado de data
=> feat: ajuste para primer migrado de data

models/nodo_cuenta_contable.go, swagger/swagger.json, swagger/swagger.yml
Relacionado con udistrital/arka_cliente#885
=> feat: Update ArkaCuentasContables

.dockerignore, README.md
udistrital/tesoreria_cliente#145
=> Despliegue a release

README.md
udistrital/tesoreria_cliente#145
=> Cambio de readme para despliegue en release

models/nodo_cuenta_contable.go, swagger/swagger.json, swagger/swagger.yml
https://github.com/udistrital/contabilidad_cliente/issues/144
=> feat: ajuste parametro naturaleza

controllers/nodo_cuenta_contable.go
https://github.com/udistrital/contabilidad_cliente/issues/141
=> fix: ajuste respuesta de error
